### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by julianpoy** [ClickerMonkey/unitz-ts#11]
Hi there!

I use your package for https://github.com/julianpoy/recipesage.

I was wondering if you'd accept a PR to update some of the dependencies in this repo since they're throwing some security warnings. Admittedly they're only devDependencies but still figured I'd reach out.

**Comment by ClickerMonkey** [comment]
Yep! Great to hear its being used

**Comment by ClickerMonkey** [comment]
Also, awesome project! That's exactly the kinda thing I created this library for.

I similarly wanted to have a list of recipes, grocery lists, and an inventory/pantry list. So you could say
1. "I want to make X for Y people, based on what I already have - add what I need to my grocery list."
2. "Based on what I have what meals can I make"
3. Ingredient alternatives, etc
